-- SPDX-License-Identifier: GPL-2.0-only
-- linux-rs pattern database — the SQLite form of the rule DB + kernel
-- census, per the original project proposal ("the database becomes the
-- real product"). Rules stay authored as rulesdb/rules/*.toml (git-
-- diffable, human-editable); this schema is a QUERYABLE INDEX built from
-- them plus the Phase 1 census data, regenerated by scripts/build_db.py,
-- never hand-edited.

-- ---- kernel census (from tmp/functions.jsonl, tmp/region_census.pkl) ----

CREATE TABLE functions (
    id INTEGER PRIMARY KEY,
    file TEXT NOT NULL,
    name TEXT NOT NULL,
    line INTEGER NOT NULL,
    fp_exact TEXT NOT NULL,       -- normalised whole-function fingerprint
    fp_shape TEXT NOT NULL,       -- structure-only fingerprint
    nodes INTEGER NOT NULL,
    ncalls INTEGER NOT NULL,
    is_static INTEGER NOT NULL,
    features TEXT NOT NULL        -- JSON array: asm/goto/switch/loop
);
CREATE INDEX idx_functions_fp_exact ON functions(fp_exact);
CREATE INDEX idx_functions_fp_shape ON functions(fp_shape);
CREATE INDEX idx_functions_file ON functions(file);
CREATE INDEX idx_functions_name ON functions(name);

-- Call edges. callee_name is the raw identifier from the AST — it is NOT
-- resolved to a specific functions.id at import time, because C name
-- resolution needs full linkage info (a `static` name can be reused
-- per-TU) that the Phase-1 fingerprinter didn't record. Use the
-- `call_edges` VIEW below for a best-effort resolved join (unambiguous
-- non-static names only); for static callees, filter callee_defs by file
-- yourself.
CREATE TABLE callees (
    function_id INTEGER NOT NULL REFERENCES functions(id),
    callee_name TEXT NOT NULL
);
CREATE INDEX idx_callees_function ON callees(function_id);
CREATE INDEX idx_callees_name ON callees(callee_name);

-- Reverse index, explicit: every definition site for a given name (a name
-- can have >1 row if multiple TUs define a `static` function of that
-- name — that ambiguity is real and must stay visible, not hidden).
CREATE INDEX idx_functions_name_lookup ON functions(name, is_static);

CREATE TABLE statement_families (
    fp TEXT PRIMARY KEY,          -- normalised statement fingerprint (or MACROSTMT:<name>)
    instance_count INTEGER NOT NULL,
    exemplar_file TEXT,
    exemplar_line INTEGER,
    exemplar_snippet TEXT
);
CREATE INDEX idx_stmtfam_count ON statement_families(instance_count DESC);

-- ---- cscope cross-reference (from tmp/cscope.out, over the same 2996-TU
-- pinned corpus as the fingerprint census — see scripts/import_cscope.py)
--
-- Closes the documented gap in `callees`/`call_edges` below: an AST
-- fingerprinter has no linker/whole-program knowledge, so it cannot tell
-- WHICH definition of a `static` function a given call resolves to when
-- multiple TUs define a same-named static fn. cscope has real whole-
-- corpus symbol-table knowledge and resolves this correctly (verified
-- 2026-07-16: lib/argv_split.c's static count_argc() query-mode -3
-- returns exactly its one real caller, no cross-TU false matches).

CREATE TABLE cscope_symbols (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,      -- 'definition' | 'call' | 'assignment' | 'text'
    file TEXT NOT NULL,
    line INTEGER NOT NULL,
    context TEXT             -- the calling/enclosing function name, when cscope reports one
);
CREATE INDEX idx_cscope_name ON cscope_symbols(name);
CREATE INDEX idx_cscope_kind ON cscope_symbols(kind);
CREATE INDEX idx_cscope_file ON cscope_symbols(file);

-- ---- sparse diagnostics (from a LOCALLY-BUILT sparse, not the Fedora
-- package — see scripts/import_sparse.py and docs/patterns-db.md.
-- Fedora's sparse 0.6.4 cannot parse this kernel version at all
-- (rejects __typeof_unqual__, required by include/asm-generic/rwonce.h
-- and others); upstream kernel.org sparse HEAD (mirrored locally at
-- /mnt/2tb/git_mirror/sparse/) has __typeof_unqual__ support and parses
-- cleanly. The build lives entirely under tmp/ (gitignored, rebuilt on
-- demand) — never a vendored binary in this repo, per Dan's decision
-- 2026-07-16.
--
-- Kernel-native semantic checks (address-space annotations, endianness,
-- context imbalance) that generic tools have no model for at all —
-- genuinely new information, not a re-derivation of anything else here.

CREATE TABLE sparse_diagnostics (
    id INTEGER PRIMARY KEY,
    file TEXT NOT NULL,
    line INTEGER NOT NULL,
    col INTEGER,
    severity TEXT NOT NULL,   -- 'warning' | 'error'
    message TEXT NOT NULL
);
CREATE INDEX idx_sparse_file ON sparse_diagnostics(file);
CREATE INDEX idx_sparse_severity ON sparse_diagnostics(severity);

-- ---- rule DB (from rulesdb/rules/*.toml) ----

CREATE TABLE rules (
    id TEXT PRIMARY KEY,          -- e.g. "fls-family"
    number INTEGER NOT NULL,      -- e.g. 6, from the filename prefix
    version INTEGER NOT NULL,
    tier INTEGER NOT NULL,
    category TEXT NOT NULL,
    match_c TEXT,
    match_family TEXT,
    emit_kind TEXT,
    emit_rust TEXT,
    derivation TEXT,
    oracle TEXT,
    human_review INTEGER NOT NULL,
    deferred INTEGER NOT NULL DEFAULT 0,   -- true if [status] block present (not yet applied)
    source_path TEXT NOT NULL              -- rulesdb/rules/NNNN-*.toml, for round-tripping to the authored file
);
CREATE INDEX idx_rules_tier ON rules(tier);
CREATE INDEX idx_rules_deferred ON rules(deferred);

CREATE TABLE rule_constraints (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    constraint_text TEXT NOT NULL
);
CREATE TABLE rule_negatives (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    negative_text TEXT NOT NULL
);
CREATE TABLE rule_evidence (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    evidence_text TEXT NOT NULL
);
CREATE TABLE rule_validation_instances (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    instance_text TEXT NOT NULL   -- "file:symbol" form as authored, not parsed further
);

-- ---- translation status (from linux-riscv/lib/**/*_rs.rs + git log) ----

CREATE TABLE translated_tus (
    c_file TEXT PRIMARY KEY,      -- relative to linux-riscv/, e.g. "lib/bcd.c"
    rs_file TEXT NOT NULL,
    landed_at TEXT,               -- commit date, ISO 8601
    patch_number INTEGER
);
CREATE INDEX idx_translated_tus_cfile ON translated_tus(c_file);

-- c2rust baseline/triage runs (scripts/run_c2rust_baseline.py): one row
-- per (c_file, run) so re-running after a c2rust fork fix shows progress
-- over time rather than overwriting history. outcome is c2rust's own
-- result, independent of translated_tus — a TU can be manually landed
-- AND separately have a c2rust attempt on record (e.g. as a differential
-- check, or from before it was hand-translated).
CREATE TABLE c2rust_attempts (
    id INTEGER PRIMARY KEY,
    c_file TEXT NOT NULL,          -- relative to linux-riscv/, e.g. "lib/bcd.c"
    run_at TEXT NOT NULL,          -- ISO 8601, when this baseline run happened
    outcome TEXT NOT NULL,         -- crash | no_output | dropped_decls | clean
    returncode INTEGER,
    warnings INTEGER,
    missing_top_level_nodes INTEGER,
    missing_children INTEGER,
    label_address_exprs INTEGER,
    rs_files_emitted INTEGER,
    c2rust_rev TEXT,               -- awtoau/c2rust git rev used for this run
    notes TEXT
);
CREATE INDEX idx_c2rust_attempts_cfile ON c2rust_attempts(c_file);
CREATE INDEX idx_c2rust_attempts_outcome ON c2rust_attempts(outcome);

-- Individual failure SIGNATURES extracted from each attempt's log —
-- one row per distinct (kind, detail) occurrence, so recurring failure
-- classes (e.g. "GNU address-of-label in _THIS_IP_", "panic at
-- conversion.rs:1024 TagTypeUnknown") surface as queryable patterns
-- across the whole corpus, not just per-file pass/fail counts.
-- 2026-07-17, Dan's request: "extract the issues... so we get patterns
-- of failures".
CREATE TABLE c2rust_failure_signatures (
    id INTEGER PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES c2rust_attempts(id),
    c_file TEXT NOT NULL,
    kind TEXT NOT NULL,        -- panic | missing_top_level_node | missing_child |
                                -- label_address | ast_warning | other
    source_file TEXT,          -- header/file the failure was located in, if known
    source_line INTEGER,
    detail TEXT NOT NULL       -- the specific message/macro/tag, deduplicatable
);
CREATE INDEX idx_c2rust_failsig_cfile ON c2rust_failure_signatures(c_file);
CREATE INDEX idx_c2rust_failsig_kind ON c2rust_failure_signatures(kind);
CREATE INDEX idx_c2rust_failsig_detail ON c2rust_failure_signatures(detail);

-- The actual "patterns of failure" view: distinct failure signatures
-- ranked by how many TUs they block — this is the fix-prioritization
-- queue (fix the signature blocking the most files first). Scoped to
-- the MOST RECENT run_at only — c2rust_attempts accumulates history
-- across repeated baseline runs (that's the point, for progress
-- tracking), but "what should I fix next" should reflect current
-- state, not every run ever recorded mixed together.
CREATE VIEW c2rust_failure_patterns AS
SELECT s.kind, s.detail, COUNT(DISTINCT s.c_file) AS tus_affected,
       GROUP_CONCAT(DISTINCT s.c_file) AS example_files
FROM c2rust_failure_signatures s
JOIN c2rust_attempts a ON a.id = s.attempt_id
WHERE a.run_at = (SELECT MAX(run_at) FROM c2rust_attempts)
GROUP BY s.kind, s.detail
ORDER BY tus_affected DESC;

-- Same "latest run only" scoping for the outcome-summary use case
-- (dev.py-style progress dashboard: how many clean/crash/etc RIGHT NOW).
CREATE VIEW c2rust_latest_run_summary AS
SELECT outcome, COUNT(*) AS n
FROM c2rust_attempts
WHERE run_at = (SELECT MAX(run_at) FROM c2rust_attempts)
GROUP BY outcome
ORDER BY n DESC;

-- Upstream immunant/c2rust intel: forks, issues, PRs — so before writing
-- our own fix we can check "has someone already solved this" in one
-- query instead of manually re-searching GitHub every time. 2026-07-17,
-- Dan's request: "make a database of all known issue and forks issue
-- and pr and patchs so we can quickly check for existing code before we
-- write our own". Populated by scripts/crawl_c2rust_upstream.py, NOT
-- wired into dev.py db (occasional/manual, like c2rust_attempts) —
-- preserved across build_db.py rebuilds the same way.
CREATE TABLE c2rust_forks (
    id INTEGER PRIMARY KEY,        -- GitHub repo id
    full_name TEXT NOT NULL UNIQUE, -- "owner/repo"
    html_url TEXT NOT NULL,
    pushed_at TEXT,                -- ISO 8601, last push — staleness signal
    ahead_by INTEGER,              -- commits ahead of immunant/c2rust master, if known
    stargazers_count INTEGER,
    default_branch TEXT,
    crawled_at TEXT NOT NULL
);
CREATE INDEX idx_c2rust_forks_pushed ON c2rust_forks(pushed_at);

CREATE TABLE c2rust_issues (
    id INTEGER PRIMARY KEY,        -- GitHub issue id (global, not per-repo number)
    repo TEXT NOT NULL,            -- "owner/repo" (immunant/c2rust or a fork)
    number INTEGER NOT NULL,
    title TEXT NOT NULL,
    state TEXT NOT NULL,           -- open | closed
    is_pr INTEGER NOT NULL,        -- 1 if this is actually a PR (GitHub's API unifies them)
    labels TEXT,                   -- comma-joined
    html_url TEXT NOT NULL,
    body TEXT,
    created_at TEXT,
    updated_at TEXT,
    closed_at TEXT,
    merged INTEGER,                -- PRs only: 1 if merged, 0 if closed-unmerged, NULL if open/not-a-PR
    crawled_at TEXT NOT NULL
);
CREATE INDEX idx_c2rust_issues_repo ON c2rust_issues(repo);
CREATE INDEX idx_c2rust_issues_state ON c2rust_issues(state);
CREATE INDEX idx_c2rust_issues_ispr ON c2rust_issues(is_pr);

-- FTS5 full-text index over issue/PR title+body — the actual "check for
-- existing code before we write our own" search surface (e.g. MATCH
-- '"address of label" OR TagTypeUnknown OR AddrLabelExpr').
CREATE VIRTUAL TABLE c2rust_issues_fts USING fts5(
    repo, number UNINDEXED, title, body, content='c2rust_issues', content_rowid='id'
);

-- Time-series project-progress snapshots — NOT ephemeral, preserved
-- across build_db.py rebuilds same as the c2rust_* tables above (see
-- PERSISTENT_TABLES in build_db.py). One row per point-in-time
-- snapshot (taken via scripts/take_progress_snapshot.py, run manually
-- after landing a TU or a c2rust baseline run) so progress trends over
-- the project's actual history are queryable, not just current state.
-- 2026-07-17, Dan's request: "a stats table - not ephemeral that
-- records progress as well".
CREATE TABLE progress_snapshots (
    id INTEGER PRIMARY KEY,
    taken_at TEXT NOT NULL,        -- ISO 8601
    note TEXT,                     -- optional free-text ("landed TU 29", "post-DFExpr-fix run")
    tus_landed INTEGER NOT NULL,
    corpus_total_files INTEGER,    -- lib/*.c files actually compiled into this kernel build
    corpus_total_loc INTEGER,
    landed_loc INTEGER,
    c2rust_clean INTEGER,          -- from the most recent c2rust_attempts run at snapshot time
    c2rust_crash INTEGER,
    c2rust_dropped_decls INTEGER,
    c2rust_no_output INTEGER,
    c2rust_timeout INTEGER,
    c2rust_rev TEXT
);
CREATE INDEX idx_progress_snapshots_taken_at ON progress_snapshots(taken_at);

-- Per-TU translation progress: manual (translated_tus) status joined
-- with the MOST RECENT c2rust_attempts row for that file, so one query
-- answers "what's done, how (manual/c2rust), and if c2rust failed, why"
-- — the relational progress table requested 2026-07-17.
CREATE VIEW tu_translation_progress AS
SELECT
  t.c_file,
  (tt.c_file IS NOT NULL) AS manually_translated,
  tt.rs_file, tt.landed_at, tt.patch_number,
  latest.outcome AS c2rust_outcome,
  latest.run_at AS c2rust_run_at,
  latest.warnings AS c2rust_warnings,
  latest.missing_top_level_nodes AS c2rust_missing_nodes,
  latest.label_address_exprs AS c2rust_label_addr_exprs,
  latest.c2rust_rev
FROM (SELECT DISTINCT c_file FROM c2rust_attempts
      UNION SELECT c_file FROM translated_tus) t
LEFT JOIN translated_tus tt ON tt.c_file = t.c_file
LEFT JOIN c2rust_attempts latest
  ON latest.c_file = t.c_file
  AND latest.run_at = (SELECT MAX(run_at) FROM c2rust_attempts WHERE c_file = t.c_file);

-- ---- convenience views (the point of "everything relational, reverse-
-- checkable" — where is X defined, where is X called FROM, is X already
-- translated, in one join, not grep) ----

-- Every function annotated with whether ITS OWN FILE is already
-- translated. This is the honest per-function translation-status join —
-- census functions don't map 1:1 to translated symbols (we translate
-- whole TUs), so "translated" here means "this function's source file
-- has a landed _rs.rs", not "this exact function has a Rust twin".
CREATE VIEW functions_with_status AS
SELECT f.*, (t.c_file IS NOT NULL) AS tu_translated, t.rs_file, t.landed_at
FROM functions f
LEFT JOIN translated_tus t
  ON t.c_file = f.file OR t.c_file = replace(f.file, 'linux-riscv/', '');

-- Best-effort resolved call edges: caller -> definition site(s), for
-- non-static callee names only (those are unambiguous — one file defines
-- each EXPORT_SYMBOL'd/extern name; `is_static` callees can collide
-- across TUs so are deliberately EXCLUDED here rather than silently
-- resolved to the wrong site — query `functions WHERE name=? AND
-- is_static=1` yourself and disambiguate by file/directory).
CREATE VIEW call_edges AS
SELECT
  caller.id   AS caller_id,   caller.file AS caller_file,   caller.name AS caller_name,
  callee.id   AS callee_id,   callee.file AS callee_file,   callee.name AS callee_name
FROM callees c
JOIN functions caller ON caller.id = c.function_id
JOIN functions callee ON callee.name = c.callee_name AND callee.is_static = 0;

-- Reverse lookup driver: for a translated TU, which of ITS census
-- functions' callees are themselves already translated (their file has a
-- landed _rs.rs) vs still C-only — a real dependency-readiness check,
-- not the vocabulary-overlap heuristic scripts/readiness.py uses.
CREATE VIEW tu_dependency_status AS
SELECT
  caller_file, caller_name, callee_file, callee_name,
  EXISTS (SELECT 1 FROM translated_tus t WHERE t.c_file = callee_file) AS callee_translated
FROM call_edges;

-- cscope-resolved call edges: supersedes `call_edges` for static callees
-- (which call_edges deliberately excludes — see its comment). A cscope
-- "call" ref's `context` column is the enclosing (caller) function; join
-- that against a cscope "definition" ref for the same name to get a
-- real, whole-corpus-resolved caller->definition-site edge, static or
-- not. Still honestly ambiguous when the SAME name is `static` in TWO+
-- files AND the caller's own file doesn't match either — those rows
-- surface with definition_ambiguous=1 rather than guessing.
CREATE VIEW cscope_call_edges AS
SELECT
  callref.file AS caller_file, callref.context AS caller_name,
  callref.name AS callee_name, callref.line AS call_line,
  defs.file AS callee_file, defs.line AS callee_line,
  (SELECT COUNT(*) FROM cscope_symbols d2
     WHERE d2.kind='definition' AND d2.name=callref.name) > 1 AS definition_ambiguous
FROM cscope_symbols callref
LEFT JOIN cscope_symbols defs
  ON defs.kind='definition' AND defs.name=callref.name
WHERE callref.kind='call';

-- Which statement families in the census are NOT yet backed by any rule's
-- match text (rough proxy via LIKE — a real matcher is scripts/readiness.py's
-- job; this view is for quick manual "what's uncovered" queries).
CREATE VIEW uncovered_hot_families AS
SELECT sf.fp, sf.instance_count, sf.exemplar_file, sf.exemplar_line, sf.exemplar_snippet
FROM statement_families sf
WHERE sf.instance_count > 10
  AND NOT EXISTS (
    SELECT 1 FROM rules r
    WHERE r.match_family IS NOT NULL AND sf.fp LIKE '%' || r.match_family || '%'
  )
ORDER BY sf.instance_count DESC;

-- Rule DB coverage summary by tier.
CREATE VIEW rule_tier_summary AS
SELECT tier, category, COUNT(*) AS n, SUM(deferred) AS n_deferred
FROM rules GROUP BY tier, category ORDER BY tier, category;

-- sparse's genuinely high-signal subset: __user/__iomem/__rcu address-
-- space misuse. Real-world measurement (2026-07-16, this corpus):
-- 214,271 total diagnostics, but 214,043 are 'warning' and dominated by
-- style noise this codebase doesn't care about (79% alone is "mixing
-- declarations and code", a C89-vs-later style check; a further chunk
-- is a false-positive-looking "non-constant initializer for static
-- object" this sparse build emits on plain integer-constant-expression
-- initializers). Only 651 rows are the address-space class sparse is
-- actually unique for — filter to THIS view, not the raw table, for
-- anything meant to inform a translation decision.
CREATE VIEW sparse_address_space_findings AS
SELECT file, line, col, severity, message FROM sparse_diagnostics
WHERE message LIKE '%address space%'
ORDER BY file, line;

-- Per-rule conformance check of c2rust's CURRENT raw output against each
-- of the 27 linux-rs rules: does c2rust already emit rule-conformant Rust
-- for a given construct (e.g. likely()/unlikely() hint already dropped
-- cleanly, rule 0007), or does it violate the rule (e.g. fls()/__fls()
-- transliterated as a literal bit-scan loop instead of the required
-- leading_zeros()-with-BITS-offset rewrite, rule 0006)? This is the
-- prioritization signal for future c2rust patch work — don't patch what's
-- already fine. Populated by scripts/check_c2rust_rule_conformance.py,
-- a current-state SNAPSHOT (each run replaces prior rows, unlike
-- c2rust_attempts' accumulating history) — but like c2rust_attempts this
-- is an occasional/manual analysis pass, not re-derived from the rules/
-- census on every routine build_db.py rebuild, so it gets the same
-- preserve-across-DB.unlink() treatment.
CREATE TABLE c2rust_rule_conformance (
    id INTEGER PRIMARY KEY,
    rule_id TEXT NOT NULL,         -- matches rules.id, e.g. "fls-family"
    c_file TEXT,                   -- relative to linux-riscv/, NULL if rule-level (not per-file)
    rust_file TEXT,                -- relative to repo root, NULL if rule-level
    line INTEGER,
    status TEXT NOT NULL,          -- conformant | violation | ambiguous | not_checkable | not_applicable
    detail TEXT NOT NULL,
    checked_at TEXT NOT NULL       -- ISO 8601, when this check run happened
);
CREATE INDEX idx_c2rust_ruleconf_rule ON c2rust_rule_conformance(rule_id);
CREATE INDEX idx_c2rust_ruleconf_status ON c2rust_rule_conformance(status);

-- Fix-prioritization queue: which rules have confirmed violations right
-- now, ranked by how many distinct files hit them — the concrete "patch
-- c2rust for this next" list.
CREATE VIEW c2rust_rule_violations_summary AS
SELECT rule_id, COUNT(*) AS n_violations, COUNT(DISTINCT rust_file) AS files_affected,
       GROUP_CONCAT(DISTINCT rust_file) AS example_files
FROM c2rust_rule_conformance
WHERE status = 'violation'
GROUP BY rule_id
ORDER BY files_affected DESC;
