-- SPDX-License-Identifier: GPL-2.0-only
-- linux-rs pattern database — the SQLite form of the rule DB + kernel
-- census, per the original project proposal ("the database becomes the
-- real product"). Rules stay authored as rulesdb/rules/*.toml (git-
-- diffable, human-editable); this schema is a QUERYABLE INDEX built from
-- them plus the Phase 1 census data, regenerated by scripts/build_db.py,
-- never hand-edited.

-- ---- kernel census (from tmp/functions.jsonl, tmp/region_census.pkl) ----

CREATE TABLE functions (
    id INTEGER PRIMARY KEY,
    file TEXT NOT NULL,
    name TEXT NOT NULL,
    line INTEGER NOT NULL,
    fp_exact TEXT NOT NULL,       -- normalised whole-function fingerprint
    fp_shape TEXT NOT NULL,       -- structure-only fingerprint
    nodes INTEGER NOT NULL,
    ncalls INTEGER NOT NULL,
    is_static INTEGER NOT NULL,
    features TEXT NOT NULL        -- JSON array: asm/goto/switch/loop
);
CREATE INDEX idx_functions_fp_exact ON functions(fp_exact);
CREATE INDEX idx_functions_fp_shape ON functions(fp_shape);
CREATE INDEX idx_functions_file ON functions(file);
CREATE INDEX idx_functions_name ON functions(name);

-- Call edges. callee_name is the raw identifier from the AST — it is NOT
-- resolved to a specific functions.id at import time, because C name
-- resolution needs full linkage info (a `static` name can be reused
-- per-TU) that the Phase-1 fingerprinter didn't record. Use the
-- `call_edges` VIEW below for a best-effort resolved join (unambiguous
-- non-static names only); for static callees, filter callee_defs by file
-- yourself.
CREATE TABLE callees (
    function_id INTEGER NOT NULL REFERENCES functions(id),
    callee_name TEXT NOT NULL
);
CREATE INDEX idx_callees_function ON callees(function_id);
CREATE INDEX idx_callees_name ON callees(callee_name);

-- Reverse index, explicit: every definition site for a given name (a name
-- can have >1 row if multiple TUs define a `static` function of that
-- name — that ambiguity is real and must stay visible, not hidden).
CREATE INDEX idx_functions_name_lookup ON functions(name, is_static);

CREATE TABLE statement_families (
    fp TEXT PRIMARY KEY,          -- normalised statement fingerprint (or MACROSTMT:<name>)
    instance_count INTEGER NOT NULL,
    exemplar_file TEXT,
    exemplar_line INTEGER,
    exemplar_snippet TEXT
);
CREATE INDEX idx_stmtfam_count ON statement_families(instance_count DESC);

-- ---- cscope cross-reference (from tmp/cscope.out, over the same 2996-TU
-- pinned corpus as the fingerprint census — see scripts/import_cscope.py)
--
-- Closes the documented gap in `callees`/`call_edges` below: an AST
-- fingerprinter has no linker/whole-program knowledge, so it cannot tell
-- WHICH definition of a `static` function a given call resolves to when
-- multiple TUs define a same-named static fn. cscope has real whole-
-- corpus symbol-table knowledge and resolves this correctly (verified
-- 2026-07-16: lib/argv_split.c's static count_argc() query-mode -3
-- returns exactly its one real caller, no cross-TU false matches).

CREATE TABLE cscope_symbols (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,      -- 'definition' | 'call' | 'assignment' | 'text'
    file TEXT NOT NULL,
    line INTEGER NOT NULL,
    context TEXT             -- the calling/enclosing function name, when cscope reports one
);
CREATE INDEX idx_cscope_name ON cscope_symbols(name);
CREATE INDEX idx_cscope_kind ON cscope_symbols(kind);
CREATE INDEX idx_cscope_file ON cscope_symbols(file);

-- ---- sparse diagnostics (from a LOCALLY-BUILT sparse, not the Fedora
-- package — see scripts/import_sparse.py and docs/patterns-db.md.
-- Fedora's sparse 0.6.4 cannot parse this kernel version at all
-- (rejects __typeof_unqual__, required by include/asm-generic/rwonce.h
-- and others); upstream kernel.org sparse HEAD (mirrored locally at
-- /mnt/2tb/git_mirror/sparse/) has __typeof_unqual__ support and parses
-- cleanly. The build lives entirely under tmp/ (gitignored, rebuilt on
-- demand) — never a vendored binary in this repo, per Dan's decision
-- 2026-07-16.
--
-- Kernel-native semantic checks (address-space annotations, endianness,
-- context imbalance) that generic tools have no model for at all —
-- genuinely new information, not a re-derivation of anything else here.

CREATE TABLE sparse_diagnostics (
    id INTEGER PRIMARY KEY,
    file TEXT NOT NULL,
    line INTEGER NOT NULL,
    col INTEGER,
    severity TEXT NOT NULL,   -- 'warning' | 'error'
    message TEXT NOT NULL
);
CREATE INDEX idx_sparse_file ON sparse_diagnostics(file);
CREATE INDEX idx_sparse_severity ON sparse_diagnostics(severity);

-- ---- rule DB (from rulesdb/rules/*.toml) ----

CREATE TABLE rules (
    id TEXT PRIMARY KEY,          -- e.g. "fls-family"
    number INTEGER NOT NULL,      -- e.g. 6, from the filename prefix
    version INTEGER NOT NULL,
    tier INTEGER NOT NULL,
    category TEXT NOT NULL,
    match_c TEXT,
    match_family TEXT,
    emit_kind TEXT,
    emit_rust TEXT,
    derivation TEXT,
    oracle TEXT,
    human_review INTEGER NOT NULL,
    deferred INTEGER NOT NULL DEFAULT 0,   -- true if [status] block present (not yet applied)
    source_path TEXT NOT NULL              -- rulesdb/rules/NNNN-*.toml, for round-tripping to the authored file
);
CREATE INDEX idx_rules_tier ON rules(tier);
CREATE INDEX idx_rules_deferred ON rules(deferred);

CREATE TABLE rule_constraints (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    constraint_text TEXT NOT NULL
);
CREATE TABLE rule_negatives (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    negative_text TEXT NOT NULL
);
CREATE TABLE rule_evidence (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    evidence_text TEXT NOT NULL
);
CREATE TABLE rule_validation_instances (
    rule_id TEXT NOT NULL REFERENCES rules(id),
    instance_text TEXT NOT NULL   -- "file:symbol" form as authored, not parsed further
);

-- ---- translation status (from linux-riscv/lib/**/*_rs.rs + git log) ----

CREATE TABLE translated_tus (
    c_file TEXT PRIMARY KEY,      -- relative to linux-riscv/, e.g. "lib/bcd.c"
    rs_file TEXT NOT NULL,
    landed_at TEXT,               -- commit date, ISO 8601
    patch_number INTEGER
);
CREATE INDEX idx_translated_tus_cfile ON translated_tus(c_file);

-- ---- convenience views (the point of "everything relational, reverse-
-- checkable" — where is X defined, where is X called FROM, is X already
-- translated, in one join, not grep) ----

-- Every function annotated with whether ITS OWN FILE is already
-- translated. This is the honest per-function translation-status join —
-- census functions don't map 1:1 to translated symbols (we translate
-- whole TUs), so "translated" here means "this function's source file
-- has a landed _rs.rs", not "this exact function has a Rust twin".
CREATE VIEW functions_with_status AS
SELECT f.*, (t.c_file IS NOT NULL) AS tu_translated, t.rs_file, t.landed_at
FROM functions f
LEFT JOIN translated_tus t
  ON t.c_file = f.file OR t.c_file = replace(f.file, 'linux-riscv/', '');

-- Best-effort resolved call edges: caller -> definition site(s), for
-- non-static callee names only (those are unambiguous — one file defines
-- each EXPORT_SYMBOL'd/extern name; `is_static` callees can collide
-- across TUs so are deliberately EXCLUDED here rather than silently
-- resolved to the wrong site — query `functions WHERE name=? AND
-- is_static=1` yourself and disambiguate by file/directory).
CREATE VIEW call_edges AS
SELECT
  caller.id   AS caller_id,   caller.file AS caller_file,   caller.name AS caller_name,
  callee.id   AS callee_id,   callee.file AS callee_file,   callee.name AS callee_name
FROM callees c
JOIN functions caller ON caller.id = c.function_id
JOIN functions callee ON callee.name = c.callee_name AND callee.is_static = 0;

-- Reverse lookup driver: for a translated TU, which of ITS census
-- functions' callees are themselves already translated (their file has a
-- landed _rs.rs) vs still C-only — a real dependency-readiness check,
-- not the vocabulary-overlap heuristic scripts/readiness.py uses.
CREATE VIEW tu_dependency_status AS
SELECT
  caller_file, caller_name, callee_file, callee_name,
  EXISTS (SELECT 1 FROM translated_tus t WHERE t.c_file = callee_file) AS callee_translated
FROM call_edges;

-- cscope-resolved call edges: supersedes `call_edges` for static callees
-- (which call_edges deliberately excludes — see its comment). A cscope
-- "call" ref's `context` column is the enclosing (caller) function; join
-- that against a cscope "definition" ref for the same name to get a
-- real, whole-corpus-resolved caller->definition-site edge, static or
-- not. Still honestly ambiguous when the SAME name is `static` in TWO+
-- files AND the caller's own file doesn't match either — those rows
-- surface with definition_ambiguous=1 rather than guessing.
CREATE VIEW cscope_call_edges AS
SELECT
  callref.file AS caller_file, callref.context AS caller_name,
  callref.name AS callee_name, callref.line AS call_line,
  defs.file AS callee_file, defs.line AS callee_line,
  (SELECT COUNT(*) FROM cscope_symbols d2
     WHERE d2.kind='definition' AND d2.name=callref.name) > 1 AS definition_ambiguous
FROM cscope_symbols callref
LEFT JOIN cscope_symbols defs
  ON defs.kind='definition' AND defs.name=callref.name
WHERE callref.kind='call';

-- Which statement families in the census are NOT yet backed by any rule's
-- match text (rough proxy via LIKE — a real matcher is scripts/readiness.py's
-- job; this view is for quick manual "what's uncovered" queries).
CREATE VIEW uncovered_hot_families AS
SELECT sf.fp, sf.instance_count, sf.exemplar_file, sf.exemplar_line, sf.exemplar_snippet
FROM statement_families sf
WHERE sf.instance_count > 10
  AND NOT EXISTS (
    SELECT 1 FROM rules r
    WHERE r.match_family IS NOT NULL AND sf.fp LIKE '%' || r.match_family || '%'
  )
ORDER BY sf.instance_count DESC;

-- Rule DB coverage summary by tier.
CREATE VIEW rule_tier_summary AS
SELECT tier, category, COUNT(*) AS n, SUM(deferred) AS n_deferred
FROM rules GROUP BY tier, category ORDER BY tier, category;

-- sparse's genuinely high-signal subset: __user/__iomem/__rcu address-
-- space misuse. Real-world measurement (2026-07-16, this corpus):
-- 214,271 total diagnostics, but 214,043 are 'warning' and dominated by
-- style noise this codebase doesn't care about (79% alone is "mixing
-- declarations and code", a C89-vs-later style check; a further chunk
-- is a false-positive-looking "non-constant initializer for static
-- object" this sparse build emits on plain integer-constant-expression
-- initializers). Only 651 rows are the address-space class sparse is
-- actually unique for — filter to THIS view, not the raw table, for
-- anything meant to inform a translation decision.
CREATE VIEW sparse_address_space_findings AS
SELECT file, line, col, severity, message FROM sparse_diagnostics
WHERE message LIKE '%address space%'
ORDER BY file, line;
